version: '2'
# ************ README ****************
# Reads env vars from .env
# Requires docker-compose version 1.7+
# ************************************

services:
  proxy:
    build: proxy/
    expose:
      - "80"
    ports:
      - "80:80"
    links:
      - api
      - frontend
    networks:
      - candytwo-network

  api:
    build: ./api
    volumes:
      - "$PWD/api:/var/www"
    networks:
      - candytwo-network

  frontend:
    build: client/
    volumes:
      - "$PWD/client/public:/www/data"
      - "$PWD/client/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - candytwo-network

networks:
  candytwo-network:
    driver: bridge
